["The first principle is that you must not fool yourself - and you are the easiest person to fool.", 
"The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark.", 
"I would rather have a mind opened by wonder than one closed by belief.", 
"What you are is what you have been. What you'll be is what you do now.", 
"What we see is mainly what we look for.", 
"A friend is someone who understands your past, believes in your future, and accepts you just the way you are.", 
"Be kind, for everyone you meet is fighting a hard battle.", 
"Joy is what happens to us when we allow ourselves to recognize how good things really are.", 
"Happiness is when what you think, what you say, and what you do are in harmony.", 
"When you doubt your power, you give power to your doubt.", 
"We must accept finite disappointment, but never lose infinite hope.",
"You, yourself, as much as anybody in the entire universe, deserve your love and affection.", 
"We come to love not by finding a perfect person, but by learning to see an imperfect person perfectly.", 
"Fear makes strangers of those who would be friends.", 
"Logic will get you from A to B. Imagination will take you everywhere.", 
"The excitement of learning separates youth from old age. As long as you're learning, you're not old.",
"Silence is a source of great strength.", 
"He who deliberates fully before taking a step will spend his entire life on one leg.", 
"There is not one big cosmic meaning for all, there is only the meaning we each give to our life.", 
"We cannot see our reflection in running water. It is only in still water that we can.", 
"Don't walk in front of me; I may not follow. Don't walk behind me; I may not lead. Just walk beside me and be my friend.", 
"Freedom is what you do with what's been done to you.",
"One who asks a question is a fool for a minute; one who does not remains a fool forever.", 
"Problems are the price of progress.",
"Being happy doesn't mean that everything is perfect. It means you've decided to look beyond the imperfections.", 
"Strength does not come from physical capacity. It comes from an indomitable will.", 
"If you have made mistakes, there is always another chance. You may have a fresh start any moment you choose.", 
"To the world you may be just one person, but to one person, you may be the world.", 
"Impossibilities are merely things which we have not yet learned.",
"You can only grow if you're willing to feel awkward and uncomfortable when you try something new.", 
"Nothing in the cry of cicadas suggests they are about to die",
"Above all, be true to yourself, and if you cannot put your heart in it, take yourself out of it.", 
"Strangers are friends you have yet to meet.", 
"Confidence is preparation. Everything else is beyond your control.", 
"Happiness is not something ready made. It comes from your own actions.", 
"Doing your best means never stop trying.", 
"Integrity is telling myself the truth. And honesty is telling the truth to other people.", 
"Good judgement comes with experience. Unfortunately, the experience usually comes from bad judgement.", 
"Well done is better than well said.", 
"Meet the first beginnings. Look to the budding mischief before it has time to ripen to maturity.", 
"As human beings, our greatness lies not so much in being able to remake the world]